-- MySQL Script generated by MySQL Workbench
-- Wed Sep 11 15:58:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_ecsus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_ecsus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_ecsus` DEFAULT CHARACTER SET utf8 ;
USE `bd_ecsus` ;

-- -----------------------------------------------------
-- Table `bd_ecsus`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ecsus`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nm_usuario` VARCHAR(15) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_ecsus`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ecsus`.`comentario` (
  `idcomentario` INT(11) NOT NULL,
  `nm_usuario` VARCHAR(15) NOT NULL,
  `comentario` VARCHAR(250) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idcomentario`),
  INDEX `fk_comentarios_usuario_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_comentarios_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `bd_ecsus`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_ecsus`.`fonte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ecsus`.`fonte` (
  `idfonte` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `imagem` VARCHAR(45) NOT NULL,
  `link` VARCHAR(45) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idfonte`),
  INDEX `fk_fonte_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_fonte_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `bd_ecsus`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
